---
title: "Técnicas Avanzadas de Estadística"
author: "[Javier Cara](https://www.javiercara.com/)"
date: "curso 2022-23"
output: 
  html_document:
    number_sections: true
    toc: false
    toc_depth: 2
  pdf_document:
    toc: true
---

<br>

***

# Contenido

## Regresión lineal

1. Modelo de regresión lineal
    a. [Modelo con un regresor](lm_modelo_1regresor.html) [(pdf)](lm_modelo_1regresor.pdf)
    b. Modelo con dos regresores
    c. [Modelo con K regresores](lm_modelo_Kregresores.html) [(pdf)](lm_modelo_Kregresores.pdf)
    d. [Estimación del modelo con la función lm](lm_modelo_lm.html) [(pdf)](lm_modelo_lm.pdf)
    e. [Regresores cualitativos](lm_modelo_cualitativas.html) [(pdf)](lm_modelo_cualitativas.pdf)


# Bibliografía

Los libros utilizados en la redacción de estos apuntes han sido, fundamentalmente:

- **[Faraway2014]** Linear models with R. Julian J. Faraway. Chapman and Hall/CRC. Edicion 2, 2014.
- **[Gelman2007]** Data Analysis Using Regression and Multilevel/Hierarchical Models. Andrew Gelman, Jennifer Hill. Cambridge University Press. 2007.
- **[James2017]** An Introduction to Statistical Learning: with Applications in R. Gareth James, Daniela Witten, Trevor Hastie and Rob Tibshirani. Springer, 2017.
- **[Montgomery2013]** Introduction to Linear Regression Analysis. Douglas Montgomery, Elisabeth Peck, Geofrey Vining . Editorial Wiley-Blackwell, Edicion 5, 2013.
- **[Peña2010]** Regresión y diseño de experimentos. Daniel Peña. Alianza Editorial, 2010.
- **[Sheather2009]** A modern approach to regression with R. Simon J. Sheather. Springer tests in Statistics, 2009.

# Archivos de datos

- [Advertising.csv](datos/Advertising.csv). Mas información en [James2017].
- [cerezos.txt](datos/cerezos.txt)
- [coches.txt](datos/coches.txt)
- [kidiq.csv](datos/kidiq.csv). Mas información en [Gelman2007].
- [Hitters.csv](datos/Hitters.csv). Mas información en [James2017].
- [Wage.csv](datos/Wage.csv). Mas información en [James2017].

# Funciones

- [cross_val_pos()](funciones/cross_val_pos.R).
- [MSE()](funciones/MSE.R)
- [predict.regsubsets()](funciones/regsubsets_predict.R).



<br>